version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/frontend"
      schedule:
          interval: "daily"
          time: "08:00"
      groups:
          frontend-npm-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "weekly"
          time: "08:00"
      groups:
          docker-dependencies:
              patterns:
                  - "*"

    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
          time: "08:00"
      groups:
          root-pip-dependencies:
              patterns:
                  - "*"
