server {
    listen 8081;

    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # do not cache sw or manifest
    location = /manifest.webmanifest {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    }

    location = /nextbus.js {
        proxy_pass https://umami.orbitix.dev/script.js;
    }
}