server {
    listen 8081;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # manifest
    location = /manifest.webmanifest {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    }

    # website
    location / {
        try_files $uri $uri/ /index.html;
    }
}