services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fly
    ports:
    - "80:80"
    - "8000:8000"
    environment:
      - REDIS_HOST=redis://localhost:6379
    depends_on:
      - redis
    networks:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  web:
    driver: bridge