services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - web

    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - web


volumes:
  redis_data:

  
networks:
  web:
    driver: bridge