
services:
  db:
    image: nickblah/postgis:13-bullseye-postgis-3
    container_name: nextbus_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/core/init_db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: