# fly.toml app configuration file generated for nextbus on 2025-07-06T22:28:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextbus'
primary_region = 'lhr'


[build]
dockerfile = "Dockerfile.prod"

[[services]]
internal_port = 80
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
interval = 10000
timeout = 2000
grace_period = "10s"
restart_limit = 0
