operator_map = {
    "South Western Railway": {"code": "SWR", "color": "#007CAD"},
    "CrossCountry": {"code": "XC", "color": "#6e2067"},
    "Great Western Railway": {"code": "GWR", "color": "#0A493E"},
    "LNER": {"code": "LNER", "color": "#d50032"},
    "Avanti West Coast": {"code": "AWC", "color": "#00747a"},
    "TransPennine Express": {"code": "TPE", "color": "#512698"},
    "Northern": {"code": "NT", "color": "#1d1d1b"},
    "East Midlands Railway": {"code": "EMR", "color": "#660099"},
    "Greater Anglia": {"code": "GA", "color": "#e41f13"},
    "West Midlands Trains": {"code": "WMT", "color": "#ff8200"},
    "Chiltern Railways": {"code": "CH", "color": "#003366"},
    "London Overground": {"code": "LO", "color": "#ff6600"},
    "Thameslink": {"code": "TL", "color": "#e6007e"},
    "Southern": {"code": "SN", "color": "#00703c"},
    "Southeastern": {"code": "SE", "color": "#003366"},
    "c2c": {"code": "C2C", "color": "#e6007e"},
    "Merseyrail": {"code": "ME", "color": "#ffcb05"},
    "ScotRail": {"code": "SR", "color": "#003366"},
    "Transport for Wales": {"code": "TfW", "color": "#d30731"},
    "Heathrow Express": {"code": "HX", "color": "#5C226C"},
    "Hull Trains": {"code": "HT", "color": "#CC0066"},
    "Grand Central": {"code": "GC", "color": "#ff8200"},
    "Elizabeth line": {"code": "EL", "color": "#6950a1"},
    "Great Northern": {"code": "GN", "color": "#43165C"},
    "Lumo": {"code": "LMO", "color": "#0047CB"},
}
