"""index service_id

Revision ID: 0a6faa54c337
Revises: b3443164399b
Create Date: 2025-09-27 21:18:44.442434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a6faa54c337"
down_revision: Union[str, Sequence[str], None] = "b3443164399b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_journey_service_id"), "journey", ["service_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journey_service_id"), table_name="journey")
    # ### end Alembic commands ###
