"""nullable start date

Revision ID: 0c5d3373d046
Revises: 3d9bfdb93b4f
Create Date: 2025-10-19 17:11:43.521680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c5d3373d046"
down_revision: Union[str, Sequence[str], None] = "3d9bfdb93b4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_source_version", "start_date", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_source_version", "start_date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###
