"""stop search name

Revision ID: 2f2f5d0dcc53
Revises: b22a35879bb5
Create Date: 2025-12-01 11:48:12.587955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f2f5d0dcc53"
down_revision: Union[str, Sequence[str], None] = "b22a35879bb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stop", sa.Column("search_name", sa.String(), nullable=False, server_default="")
    )
    op.create_index(op.f("ix_stop_search_name"), "stop", ["search_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stop_search_name"), table_name="stop")
    op.drop_column("stop", "search_name")

    # ### end Alembic commands ###
