"""remove file hash from timetable

Revision ID: 38a97cc190b9
Revises: 4d2ff03cdbf4
Create Date: 2025-10-17 23:45:20.504317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38a97cc190b9"
down_revision: Union[str, Sequence[str], None] = "4d2ff03cdbf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timetable_hash"), table_name="timetable")
    op.drop_column("timetable", "hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timetable",
        sa.Column("hash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_timetable_hash"), "timetable", ["hash"], unique=False)
    # ### end Alembic commands ###
