"""init

Revision ID: 3d9bfdb93b4f
Revises:
Create Date: 2025-10-19 15:34:38.073053

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy_searchable import sql_expressions
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "3d9bfdb93b4f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sql_expressions.statement)
    op.create_table(
        "active_users_snapshot",
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("total_connections", sa.Integer(), nullable=False),
        sa.Column("unique_connections", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_index(
        op.f("ix_active_users_snapshot_timestamp"),
        "active_users_snapshot",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "bank_holiday",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bot_dashboard",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bot_status",
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_status",
            sa.Enum("up", "down", "degraded", "restarting", name="botstatusenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "calendar",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monday", sa.Boolean(), nullable=False),
        sa.Column("tuesday", sa.Boolean(), nullable=False),
        sa.Column("wednesday", sa.Boolean(), nullable=False),
        sa.Column("thursday", sa.Boolean(), nullable=False),
        sa.Column("friday", sa.Boolean(), nullable=False),
        sa.Column("saturday", sa.Boolean(), nullable=False),
        sa.Column("sunday", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("search", sa.String(), nullable=True),
        sa.Column("noc", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "operator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("noc", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_operator_search_vector",
        "operator",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "region",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "admin_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("atco_code", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("region_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_holiday_date",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bank_holiday_name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_holiday_name"],
            ["bank_holiday.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bank_holiday_name", "date", name="uq_bank_holiday_date_per_holiday"
        ),
    )
    op.create_index(
        op.f("ix_bank_holiday_date_bank_holiday_name"),
        "bank_holiday_date",
        ["bank_holiday_name"],
        unique=False,
    )
    op.create_table(
        "calendar_bank_holiday",
        sa.Column("operating", sa.Boolean(), nullable=False),
        sa.Column("bank_holiday", sa.String(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_holiday"],
            ["bank_holiday.name"],
        ),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "bank_holiday", "calendar_id", name="pk_calendar_bank_holiday"
        ),
    )
    op.create_table(
        "calendar_exception",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("operating", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("special", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "calendar_id",
            "start_date",
            "end_date",
            "operating",
            name="uq_calendar_exception",
        ),
    )
    op.create_table(
        "data_source_version",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("bods_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("etag", sa.String(), nullable=True),
        sa.Column("zip_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_code", sa.String(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("bt_service_id", sa.Integer(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column("line_name", sa.String(), nullable=False),
        sa.Column("line_brand", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("vias", sa.String(), nullable=True),
        sa.Column("public_use", sa.Boolean(), nullable=True),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTILINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("data_wrong", sa.Boolean(), nullable=False),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_bt_service_id"), "service", ["bt_service_id"], unique=False
    )
    op.create_index(op.f("ix_service_current"), "service", ["current"], unique=False)
    op.create_index(
        "ix_service_search_vector",
        "service",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_service_service_code"), "service", ["service_code"], unique=False
    )
    op.create_table(
        "district",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_area_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_area_id"],
            ["admin_area.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_import",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column("data_source_version_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_source_version_id"],
            ["data_source_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_import_file_hash"), "file_import", ["file_hash"], unique=True
    )
    op.create_table(
        "stop_area",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "lat",
            sa.Float(),
            sa.Computed(
                "ST_Y(point::geometry)",
            ),
            nullable=True,
        ),
        sa.Column(
            "lon",
            sa.Float(),
            sa.Computed(
                "ST_X(point::geometry)",
            ),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "on_street_pair",
                "on_street_cluster",
                "airport_building",
                "bus_coach_station",
                "ferry_terminal_dock",
                "tram_metro_station",
                "rail_station",
                "coach_service_coverage",
                name="stopareatypeenum",
            ),
            nullable=True,
        ),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("admin_area_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_area_id"],
            ["admin_area.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["stop_area.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timetable",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.String(), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column("data_source_version_id", sa.Integer(), nullable=True),
        sa.Column("bt_service_id", sa.Integer(), nullable=True),
        sa.Column("service_code", sa.String(), nullable=False),
        sa.Column("line_name", sa.String(), nullable=False),
        sa.Column("line_brand", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column("vias", sa.String(), nullable=True),
        sa.Column("inbound_description", sa.String(), nullable=True),
        sa.Column("outbound_description", sa.String(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTILINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("public_use", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["data_source_version_id"],
            ["data_source_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timetable_bt_service_id"), "timetable", ["bt_service_id"], unique=False
    )
    op.create_index(
        op.f("ix_timetable_service_id"), "timetable", ["service_id"], unique=False
    )
    op.create_index(
        "ix_timetable_service_line_name",
        "timetable",
        ["service_id", "line_name"],
        unique=False,
    )
    op.create_index(
        "uq_service_revision_with_nulls",
        "timetable",
        ["service_id", "revision_number", "start_date", "end_date", "data_source_id"],
        unique=True,
    )
    op.create_table(
        "locality",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("qualifier_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_area_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lat",
            sa.Float(),
            sa.Computed(
                "ST_Y(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column(
            "lon",
            sa.Float(),
            sa.Computed(
                "ST_X(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["admin_area_id"],
            ["admin_area.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["district.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["locality.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_locality_search_vector",
        "locality",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "stop",
        sa.Column("atco_code", sa.String(), nullable=False),
        sa.Column("naptan_code", sa.String(), nullable=True),
        sa.Column("common_name", sa.String(), nullable=False),
        sa.Column("common_short_name", sa.String(), nullable=True),
        sa.Column("landmark", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("crossing", sa.String(), nullable=True),
        sa.Column("indicator", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lat",
            sa.Float(),
            sa.Computed(
                "ST_Y(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column(
            "lon",
            sa.Float(),
            sa.Computed(
                "ST_X(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column("stop_area_id", sa.String(), nullable=True),
        sa.Column("locality_id", sa.String(), nullable=True),
        sa.Column("admin_area_id", sa.Integer(), nullable=True),
        sa.Column("suburb", sa.String(), nullable=True),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column("heading", sa.Integer(), nullable=True),
        sa.Column("bearing", sa.String(), nullable=True),
        sa.Column(
            "stop_type",
            sa.Enum(
                "airport_entrance",
                "airside_interchange_area",
                "ferry_terminal_entrance",
                "ferry_interchange_area",
                "ferry_berth",
                "rail_station_entrance",
                "rail_interchange_area",
                "rail_platform",
                "metro_tram_underground_entrance",
                "metro_tram_underground_access",
                "metro_tram_underground_platform",
                "bus_coach_station_entrance",
                "bus_coach_station_access",
                "bus_coach_variable_bay",
                "bus_coach_bay",
                "bus_stop",
                "taxi_rank",
                "shared_taxi_rank",
                name="stoptypeenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "bus_stop_type",
            sa.Enum(
                "marked_stop",
                "on_street_unmarked_stop",
                "on_street_hail_and_ride_section",
                "on_street_flexible_zone",
                name="busstoptypeenum",
            ),
            nullable=True,
        ),
        sa.Column("timing_status", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["admin_area_id"],
            ["admin_area.id"],
        ),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["locality.id"],
        ),
        sa.ForeignKeyConstraint(["stop_area_id"], ["stop_area.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("atco_code"),
    )
    op.create_index(op.f("ix_stop_atco_code"), "stop", ["atco_code"], unique=False)
    op.create_index(op.f("ix_stop_locality_id"), "stop", ["locality_id"], unique=False)
    op.create_index(
        "ix_stop_search_vector",
        "stop",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "journey",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("bt_trip_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_journey_code", sa.String(), nullable=True),
        sa.Column("ticket_machine_code", sa.String(), nullable=True),
        sa.Column("sequence", sa.SmallInteger(), nullable=True),
        sa.Column("block_id", sa.String(), nullable=True),
        sa.Column("inbound", sa.Boolean(), nullable=True),
        sa.Column("headsign", sa.String(), nullable=True),
        sa.Column("start_time", sa.Interval(), nullable=True),
        sa.Column("end_time", sa.Interval(), nullable=True),
        sa.Column("origin_stop_id", sa.String(), nullable=True),
        sa.Column("destination_stop_id", sa.String(), nullable=True),
        sa.Column("calendar_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["destination_stop_id"],
            ["stop.atco_code"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_stop_id"],
            ["stop.atco_code"],
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["timetable_id"], ["timetable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journey_destination_stop_id"),
        "journey",
        ["destination_stop_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journey_origin_stop_id"), "journey", ["origin_stop_id"], unique=False
    )
    op.create_index(
        op.f("ix_journey_service_id"), "journey", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_journey_timetable_id"), "journey", ["timetable_id"], unique=False
    )
    op.create_table(
        "route_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("from_stop", sa.String(), nullable=True),
        sa.Column("to_stop", sa.String(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_stop"],
            ["stop.atco_code"],
        ),
        sa.ForeignKeyConstraint(["timetable_id"], ["timetable.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["to_stop"],
            ["stop.atco_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "timetable_id", "from_stop", "to_stop", name="uq_timetable_routelink"
        ),
    )
    op.create_table(
        "service_stop_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.Column("order", sa.SmallInteger(), nullable=True),
        sa.Column("inbound", sa.Boolean(), nullable=True),
        sa.Column("line_name", sa.String(), nullable=True),
        sa.Column("timing_point", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.atco_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_stop_usage_service_id"),
        "service_stop_usage",
        ["service_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_stop_usage_stop_id"),
        "service_stop_usage",
        ["stop_id"],
        unique=False,
    )
    op.create_index(
        "ix_stopusage_inbound_order",
        "service_stop_usage",
        ["inbound", "order"],
        unique=False,
    )
    op.create_table(
        "stop_time",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("journey_id", sa.BigInteger(), nullable=False),
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.Column("stop_sequence", sa.SmallInteger(), nullable=False),
        sa.Column("arrival_time", sa.Interval(), nullable=True),
        sa.Column("departure_time", sa.Interval(), nullable=True),
        sa.Column("dest_display", sa.String(), nullable=True),
        sa.Column(
            "timing_status",
            sa.Enum(
                "other",
                "time_info_point",
                "principal_timing_point",
                name="timingstatusenum",
            ),
            nullable=True,
        ),
        sa.Column("pick_up", sa.Boolean(), nullable=True),
        sa.Column("drop_off", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["journey_id"], ["journey.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.atco_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "journey_id", "stop_sequence", name="uq_stop_time_journey_sequence"
        ),
    )
    op.create_index(
        op.f("ix_stop_time_departure_time"),
        "stop_time",
        ["departure_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stop_time_journey_id"), "stop_time", ["journey_id"], unique=False
    )
    op.create_index(
        op.f("ix_stop_time_stop_id"), "stop_time", ["stop_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stop_time_stop_id"), table_name="stop_time")
    op.drop_index(op.f("ix_stop_time_journey_id"), table_name="stop_time")
    op.drop_index(op.f("ix_stop_time_departure_time"), table_name="stop_time")
    op.drop_table("stop_time")
    op.drop_index("ix_stopusage_inbound_order", table_name="service_stop_usage")
    op.drop_index(
        op.f("ix_service_stop_usage_stop_id"), table_name="service_stop_usage"
    )
    op.drop_index(
        op.f("ix_service_stop_usage_service_id"), table_name="service_stop_usage"
    )
    op.drop_table("service_stop_usage")
    op.drop_index(
        "idx_route_link_geometry", table_name="route_link", postgresql_using="gist"
    )
    op.drop_table("route_link")
    op.drop_index(op.f("ix_journey_timetable_id"), table_name="journey")
    op.drop_index(op.f("ix_journey_service_id"), table_name="journey")
    op.drop_index(op.f("ix_journey_origin_stop_id"), table_name="journey")
    op.drop_index(op.f("ix_journey_destination_stop_id"), table_name="journey")
    op.drop_table("journey")
    op.drop_index("ix_stop_search_vector", table_name="stop", postgresql_using="gin")
    op.drop_index(op.f("ix_stop_locality_id"), table_name="stop")
    op.drop_index(op.f("ix_stop_atco_code"), table_name="stop")
    op.drop_index("idx_stop_point", table_name="stop", postgresql_using="gist")
    op.drop_table("stop")
    op.drop_index(
        "ix_locality_search_vector", table_name="locality", postgresql_using="gin"
    )
    op.drop_index("idx_locality_point", table_name="locality", postgresql_using="gist")
    op.drop_table("locality")
    op.drop_index("uq_service_revision_with_nulls", table_name="timetable")
    op.drop_index("ix_timetable_service_line_name", table_name="timetable")
    op.drop_index(op.f("ix_timetable_service_id"), table_name="timetable")
    op.drop_index(op.f("ix_timetable_bt_service_id"), table_name="timetable")
    op.drop_index(
        "idx_timetable_geometry", table_name="timetable", postgresql_using="gist"
    )
    op.drop_table("timetable")
    op.drop_index(
        "idx_stop_area_point", table_name="stop_area", postgresql_using="gist"
    )
    op.drop_table("stop_area")
    op.drop_index(op.f("ix_file_import_file_hash"), table_name="file_import")
    op.drop_table("file_import")
    op.drop_table("district")
    op.drop_index(op.f("ix_service_service_code"), table_name="service")
    op.drop_index(
        "ix_service_search_vector", table_name="service", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_service_current"), table_name="service")
    op.drop_index(op.f("ix_service_bt_service_id"), table_name="service")
    op.drop_index("idx_service_geometry", table_name="service", postgresql_using="gist")
    op.drop_table("service")
    op.drop_table("data_source_version")
    op.drop_table("calendar_exception")
    op.drop_table("calendar_bank_holiday")
    op.drop_index(
        op.f("ix_bank_holiday_date_bank_holiday_name"), table_name="bank_holiday_date"
    )
    op.drop_table("bank_holiday_date")
    op.drop_table("admin_area")
    op.drop_table("region")
    op.drop_index(
        "ix_operator_search_vector", table_name="operator", postgresql_using="gin"
    )
    op.drop_table("operator")
    op.drop_table("data_source")
    op.drop_table("calendar")
    op.drop_table("bot_status")
    op.drop_table("bot_dashboard")
    op.drop_table("bank_holiday")
    op.drop_index(
        op.f("ix_active_users_snapshot_timestamp"), table_name="active_users_snapshot"
    )
    op.drop_table("active_users_snapshot")
    # ### end Alembic commands ###
