"""add NPTG

Revision ID: 418c05e60183
Revises: 7025cce4f9dc
Create Date: 2025-09-18 22:42:41.695445

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418c05e60183'
down_revision: Union[str, Sequence[str], None] = '7025cce4f9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('admin_area',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('atco_code', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('short_name', sa.String(), nullable=True),
                    sa.Column('country', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('region_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('district',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('admin_area_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_area_id'], ['admin_area.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('locality',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('qualifier_name', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('admin_area_id', sa.Integer(), nullable=True),
                    sa.Column('district_id', sa.Integer(), nullable=True),
                    sa.Column('parent_id', sa.String(), nullable=True),
                    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2,
                                                                  from_text='ST_GeomFromEWKT', name='geometry',
                                                                  nullable=False), nullable=False),
                    sa.Column('lat', sa.Float(), sa.Computed('ST_Y(point::geometry)', ), nullable=False),
                    sa.Column('lon', sa.Float(), sa.Computed('ST_X(point::geometry)', ), nullable=False),
                    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_area_id'], ['admin_area.id'], ),
                    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['locality.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('data_source', 'last_modified',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.add_column('stop', sa.Column('locality_id', sa.String(), nullable=True))
    op.add_column('stop', sa.Column('admin_area_id', sa.Integer(), nullable=True))
    op.alter_column('stop', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.alter_column('stop', 'modified_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    op.create_foreign_key(None, 'stop', 'locality', ['locality_id'], ['id'])
    op.create_foreign_key(None, 'stop', 'admin_area', ['admin_area_id'], ['id'])
    op.add_column('stoparea', sa.Column('admin_area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stoparea', 'admin_area', ['admin_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stoparea', type_='foreignkey')
    op.drop_column('stoparea', 'admin_area_id')
    op.drop_constraint(None, 'stop', type_='foreignkey')
    op.drop_constraint(None, 'stop', type_='foreignkey')
    op.alter_column('stop', 'modified_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('stop', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.drop_column('stop', 'admin_area_id')
    op.drop_column('stop', 'locality_id')
    op.alter_column('data_source', 'last_modified',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.drop_table('locality')
    op.drop_table('district')
    op.drop_table('admin_area')
    op.drop_table('region')
    # ### end Alembic commands ###
