"""many to many timetable data source

Revision ID: 4d5b86a8e7c4
Revises: 384d65af32c9
Create Date: 2025-09-26 00:30:31.589444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d5b86a8e7c4"
down_revision: Union[str, Sequence[str], None] = "384d65af32c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timetable_tt_data_source_link",
        sa.Column("timetable_id", sa.Integer(), nullable=False),
        sa.Column("tt_data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["timetable_id"], ["timetable.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tt_data_source_id"], ["timetable_data_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "timetable_id", "tt_data_source_id", name="pk_timetable_data_source_link"
        ),
    )
    op.create_index(
        op.f("ix_timetable_tt_data_source_link_timetable_id"),
        "timetable_tt_data_source_link",
        ["timetable_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timetable_tt_data_source_link_tt_data_source_id"),
        "timetable_tt_data_source_link",
        ["tt_data_source_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("timetable_timetable_data_source_id_fkey"), "timetable", type_="foreignkey"
    )
    op.drop_column("timetable", "timetable_data_source_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timetable",
        sa.Column(
            "timetable_data_source_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("timetable_timetable_data_source_id_fkey"),
        "timetable",
        "timetable_data_source",
        ["timetable_data_source_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_timetable_tt_data_source_link_tt_data_source_id"),
        table_name="timetable_tt_data_source_link",
    )
    op.drop_index(
        op.f("ix_timetable_tt_data_source_link_timetable_id"),
        table_name="timetable_tt_data_source_link",
    )
    op.drop_table("timetable_tt_data_source_link")
    # ### end Alembic commands ###
