"""add indexes

Revision ID: 50077591e20a
Revises: dc88f769ed36
Create Date: 2025-09-21 17:43:49.171531

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50077591e20a'
down_revision: Union[str, Sequence[str], None] = 'dc88f769ed36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_journey_destination_stop_id'), 'journey', ['destination_stop_id'], unique=False)
    op.create_index(op.f('ix_journey_line_id'), 'journey', ['line_id'], unique=False)
    op.create_index(op.f('ix_journey_origin_stop_id'), 'journey', ['origin_stop_id'], unique=False)
    op.create_index(op.f('ix_line_id'), 'line', ['id'], unique=False)
    op.create_index(op.f('ix_line_stop_usage_line_id'), 'line_stop_usage', ['line_id'], unique=False)
    op.create_index(op.f('ix_line_stop_usage_stop_id'), 'line_stop_usage', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stop_locality_id'), 'stop', ['locality_id'], unique=False)
    op.create_index(op.f('ix_stop_time_departure_time'), 'stop_time', ['departure_time'], unique=False)
    op.create_index(op.f('ix_stop_time_journey_id'), 'stop_time', ['journey_id'], unique=False)
    op.create_index(op.f('ix_stop_time_stop_id'), 'stop_time', ['stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_time_stop_id'), table_name='stop_time')
    op.drop_index(op.f('ix_stop_time_journey_id'), table_name='stop_time')
    op.drop_index(op.f('ix_stop_time_departure_time'), table_name='stop_time')
    op.drop_index(op.f('ix_stop_locality_id'), table_name='stop')
    op.drop_index(op.f('ix_line_stop_usage_stop_id'), table_name='line_stop_usage')
    op.drop_index(op.f('ix_line_stop_usage_line_id'), table_name='line_stop_usage')
    op.drop_index(op.f('ix_line_id'), table_name='line')
    op.drop_index(op.f('ix_journey_origin_stop_id'), table_name='journey')
    op.drop_index(op.f('ix_journey_line_id'), table_name='journey')
    op.drop_index(op.f('ix_journey_destination_stop_id'), table_name='journey')
    # ### end Alembic commands ###
