"""add slugs

Revision ID: 55c3035634ec
Revises: 50077591e20a
Create Date: 2025-09-22 21:19:58.671461

"""

from slugify import slugify

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from backend.models import Locality, Line


# revision identifiers, used by Alembic.
revision: str = "55c3035634ec"
down_revision: Union[str, Sequence[str], None] = "50077591e20a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("line", sa.Column("slug", sa.String(length=100), nullable=True))
    op.add_column("locality", sa.Column("slug", sa.String(length=100), nullable=True))

    bind = op.get_bind()
    session = Session(bind=bind)

    existing_line_slugs = set(
        s[0] for s in session.execute(sa.select(Line.slug)).all() if s[0] is not None
    )
    existing_locality_slugs = set(
        s[0]
        for s in session.execute(sa.select(Locality.slug)).all()
        if s[0] is not None
    )
    with session.no_autoflush:
        # Locality slugs
        for loc in session.query(Locality).order_by(Locality.id).all():
            base_slug = slugify(loc.get_full_name)[:100]  # type: ignore
            slug_candidate = base_slug
            suffix = 1
            while slug_candidate in existing_locality_slugs:
                slug_candidate = f"{base_slug[: 100 - len(f'-{suffix}')]}-{suffix}"
                suffix += 1
            loc.slug = slug_candidate  # type: ignore
            existing_locality_slugs.add(slug_candidate)

        # Line slugs
        for line in session.query(Line).order_by(Line.id).all():
            base_slug = slugify(line.get_full_name)[:100]  # type: ignore
            slug_candidate = base_slug
            suffix = 1
            while slug_candidate in existing_line_slugs:
                slug_candidate = f"{base_slug[: 100 - len(f'-{suffix}')]}-{suffix}"
                suffix += 1
            line.slug = slug_candidate  # type: ignore
            existing_line_slugs.add(slug_candidate)

    session.commit()

    op.create_unique_constraint("uq_line_slug", "line", ["slug"])
    op.create_unique_constraint("uq_locality_slug", "locality", ["slug"])

    op.alter_column("line", "slug", nullable=False)
    op.alter_column("locality", "slug", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_locality_slug", "locality", type_="unique")
    op.drop_column("locality", "slug")
    op.drop_constraint("uq_line_slug", "line", type_="unique")
    op.drop_column("line", "slug")
    # ### end Alembic commands ###
