"""many to many service operator

Revision ID: 5d97f16c4122
Revises: 0c5d3373d046
Create Date: 2025-10-19 20:22:16.385807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d97f16c4122"
down_revision: Union[str, Sequence[str], None] = "0c5d3373d046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_operator",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "operator_id"),
    )
    op.drop_constraint(op.f("service_operator_id_fkey"), "service", type_="foreignkey")
    op.drop_column("service", "operator_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service",
        sa.Column("operator_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("service_operator_id_fkey"), "service", "operator", ["operator_id"], ["id"]
    )
    op.drop_table("service_operator")
    # ### end Alembic commands ###
