"""operator ref can be string

Revision ID: 5f6e6ffb6b7e
Revises: 6eb02d3f3fef
Create Date: 2025-09-10 23:15:01.284955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f6e6ffb6b7e"
down_revision: Union[str, Sequence[str], None] = "6eb02d3f3fef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operator",
        "ref",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operator",
        "ref",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_constraint("uq_line_to_route", "line_to_route", type_="unique")
    op.drop_constraint("uq_line_stop_usage", "line_stop_usage", type_="unique")
    # ### end Alembic commands ###
