"""cascade file import

Revision ID: 62d6cbe3e53c
Revises: 9f24cf1e9752
Create Date: 2025-10-20 23:57:19.558357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62d6cbe3e53c"
down_revision: Union[str, Sequence[str], None] = "9f24cf1e9752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("file_import_data_source_version_id_fkey"),
        "file_import",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "file_import",
        "data_source_version",
        ["data_source_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file_import", type_="foreignkey")
    op.create_foreign_key(
        op.f("file_import_data_source_version_id_fkey"),
        "file_import",
        "data_source_version",
        ["data_source_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###
