"""add origin and destination stops

Revision ID: 6936d9c17187
Revises: 418c05e60183
Create Date: 2025-09-19 09:18:11.377807

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6936d9c17187'
down_revision: Union[str, Sequence[str], None] = '418c05e60183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('origin_stop_id', sa.String(), nullable=True))
    op.add_column('journey', sa.Column('destination_stop_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'journey', 'stop', ['destination_stop_id'], ['atco_code'])
    op.create_foreign_key(None, 'journey', 'stop', ['origin_stop_id'], ['atco_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journey', type_='foreignkey')
    op.drop_constraint(None, 'journey', type_='foreignkey')
    op.drop_column('journey', 'destination_stop_id')
    op.drop_column('journey', 'origin_stop_id')
    # ### end Alembic commands ###
