"""special calendar exceptions

Revision ID: 6dbc93b26af3
Revises: 096b45ae3254
Create Date: 2025-10-07 22:36:48.309075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dbc93b26af3"
down_revision: Union[str, Sequence[str], None] = "096b45ae3254"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_exception", sa.Column("special", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_exception", "special")
    # ### end Alembic commands ###
