"""initial db

Revision ID: 6eb02d3f3fef
Revises:
Create Date: 2025-09-10 23:10:50.315233

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "6eb02d3f3fef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_users_snapshot",
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("total_connections", sa.Integer(), nullable=False),
        sa.Column("unique_connections", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_index(
        op.f("ix_active_users_snapshot_timestamp"),
        "active_users_snapshot",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "bank_holiday",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bot_dashboard",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bot_status",
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_status",
            sa.Enum("up", "down", "degraded", "restarting", name="botstatusenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "calendar",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monday", sa.Boolean(), nullable=False),
        sa.Column("tuesday", sa.Boolean(), nullable=False),
        sa.Column("wednesday", sa.Boolean(), nullable=False),
        sa.Column("thursday", sa.Boolean(), nullable=False),
        sa.Column("friday", sa.Boolean(), nullable=False),
        sa.Column("saturday", sa.Boolean(), nullable=False),
        sa.Column("sunday", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "operator",
        sa.Column("noc", sa.String(), nullable=False),
        sa.Column("ref", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("noc"),
    )
    op.create_index(
        "ix_operator_search_vector",
        "operator",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "route_section",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stoparea",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "lat",
            sa.Float(),
            sa.Computed(
                "ST_Y(point::geometry)",
            ),
            nullable=True,
        ),
        sa.Column(
            "lon",
            sa.Float(),
            sa.Computed(
                "ST_X(point::geometry)",
            ),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "on_street_pair",
                "on_street_cluster",
                "airport_building",
                "bus_coach_station",
                "ferry_terminal_dock",
                "tram_metro_station",
                "rail_station",
                "coach_service_coverage",
                name="stopareatypeenum",
            ),
            nullable=True,
        ),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["stoparea.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_holiday_date",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bank_holiday_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_holiday_id"],
            ["bank_holiday.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bank_holiday_id", "date", name="uq_bank_holiday_date_per_holiday"
        ),
    )
    op.create_table(
        "calendar_bank_holiday",
        sa.Column("operating", sa.Boolean(), nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("bank_holiday_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_holiday_id"],
            ["bank_holiday.id"],
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendar.id"],
        ),
        sa.PrimaryKeyConstraint("calendar_id", "bank_holiday_id"),
    )
    op.create_table(
        "calendar_exception",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calendar_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("operating", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["calendar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("private_code", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("route_section_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_section_id"], ["route_section.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service",
        sa.Column("service_code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column("vias", sa.String(), nullable=True),
        sa.Column("operator_noc", sa.String(), nullable=True),
        sa.Column("line_names", sa.String(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["operator_noc"],
            ["operator.noc"],
        ),
        sa.PrimaryKeyConstraint("service_code"),
    )
    op.create_index(
        "ix_service_search_vector",
        "service",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "stop",
        sa.Column("atco_code", sa.String(), nullable=False),
        sa.Column("naptan_code", sa.String(), nullable=True),
        sa.Column("common_name", sa.String(), nullable=False),
        sa.Column("common_short_name", sa.String(), nullable=True),
        sa.Column("landmark", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("crossing", sa.String(), nullable=True),
        sa.Column("indicator", sa.String(), nullable=True),
        sa.Column(
            "point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "lat",
            sa.Float(),
            sa.Computed(
                "ST_Y(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column(
            "lon",
            sa.Float(),
            sa.Computed(
                "ST_X(point::geometry)",
            ),
            nullable=False,
        ),
        sa.Column("stop_area_id", sa.String(), nullable=True),
        sa.Column("suburb", sa.String(), nullable=True),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column("heading", sa.Integer(), nullable=True),
        sa.Column("bearing", sa.String(), nullable=True),
        sa.Column(
            "stop_type",
            sa.Enum(
                "airport_entrance",
                "airside_interchange_area",
                "ferry_terminal_entrance",
                "ferry_interchange_area",
                "ferry_berth",
                "rail_station_entrance",
                "rail_interchange_area",
                "rail_platform",
                "metro_tram_underground_entrance",
                "metro_tram_underground_access",
                "metro_tram_underground_platform",
                "bus_coach_station_entrance",
                "bus_coach_station_access",
                "bus_coach_variable_bay",
                "bus_coach_bay",
                "bus_stop",
                "taxi_rank",
                "shared_taxi_rank",
                name="stoptypeenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "bus_stop_type",
            sa.Enum(
                "marked_stop",
                "on_street_unmarked_stop",
                "on_street_hail_and_ride_section",
                "on_street_flexible_zone",
                name="busstoptypeenum",
            ),
            nullable=True,
        ),
        sa.Column("timing_status", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["stop_area_id"], ["stoparea.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("atco_code"),
    )
    op.create_index(op.f("ix_stop_atco_code"), "stop", ["atco_code"], unique=False)
    op.create_index(
        "ix_stop_search_vector",
        "stop",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "track_section",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_stop", sa.String(), nullable=True),
        sa.Column("to_stop", sa.String(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("route_link_ref", sa.String(), nullable=True),
        sa.Column("route_section_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_section_id"], ["route_section.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("bt_service_id", sa.Integer(), nullable=True),
        sa.Column("line_name", sa.String(), nullable=False),
        sa.Column("inbound_description", sa.String(), nullable=True),
        sa.Column("outbound_description", sa.String(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTILINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("service_code", sa.String(), nullable=False),
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["service_code"], ["service.service_code"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("line_name", "service_code", name="uq_line_per_service"),
    )
    op.create_index(
        "ix_line_search_vector",
        "line",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "journey",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("bt_trip_id", sa.Integer(), nullable=True),
        sa.Column("service_code", sa.String(), nullable=False),
        sa.Column("vehicle_journey_code", sa.String(), nullable=True),
        sa.Column("ticket_machine_code", sa.String(), nullable=True),
        sa.Column("line_id", sa.String(), nullable=True),
        sa.Column("block_id", sa.String(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("outbound", "inbound", "circular", "unknown", name="directiontype"),
            nullable=True,
        ),
        sa.Column("start_time", sa.Interval(), nullable=False),
        sa.Column("end_time", sa.Interval(), nullable=True),
        sa.Column("calendar_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["line_id"], ["line.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["service_code"], ["service.service_code"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line_stop_usage",
        sa.Column("line_id", sa.String(), nullable=False),
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["line_id"], ["line.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.atco_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("line_id", "stop_id"),
        sa.UniqueConstraint("line_id", "stop_id", name="uq_line_stop_usage"),
    )
    op.create_table(
        "line_to_route",
        sa.Column("line_id", sa.String(), nullable=False),
        sa.Column("route_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["line_id"], ["line.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("line_id", "route_id"),
        sa.UniqueConstraint("line_id", "route_id", name="uq_line_to_route"),
    )
    op.create_table(
        "stop_time",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("journey_id", sa.String(), nullable=False),
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.Column("stop_sequence", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.Interval(), nullable=True),
        sa.Column("departure_time", sa.Interval(), nullable=True),
        sa.Column("timing_status", sa.String(), nullable=True),
        sa.Column("pick_up", sa.Boolean(), nullable=True),
        sa.Column("drop_off", sa.Boolean(), nullable=True),
        sa.Column("wait_time", sa.Interval(), nullable=True),
        sa.Column("distance_traveled", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["journey_id"], ["journey.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stop_id"], ["stop.atco_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "journey_id", "stop_sequence", name="uq_stop_time_journey_sequence"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stop_time")
    op.drop_table("line_to_route")
    op.drop_table("line_stop_usage")
    op.drop_table("journey")
    op.drop_index("ix_line_search_vector", table_name="line", postgresql_using="gin")
    op.drop_index("idx_line_geometry", table_name="line", postgresql_using="gist")
    op.drop_table("line")
    op.drop_index(
        "idx_track_section_geometry",
        table_name="track_section",
        postgresql_using="gist",
    )
    op.drop_table("track_section")
    op.drop_index("ix_stop_search_vector", table_name="stop", postgresql_using="gin")
    op.drop_index(op.f("ix_stop_atco_code"), table_name="stop")
    op.drop_index("idx_stop_point", table_name="stop", postgresql_using="gist")
    op.drop_table("stop")
    op.drop_index(
        "ix_service_search_vector", table_name="service", postgresql_using="gin"
    )
    op.drop_table("service")
    op.drop_table("route")
    op.drop_table("calendar_exception")
    op.drop_table("calendar_bank_holiday")
    op.drop_table("bank_holiday_date")
    op.drop_index("idx_stoparea_point", table_name="stoparea", postgresql_using="gist")
    op.drop_table("stoparea")
    op.drop_index(
        "idx_route_section_geometry",
        table_name="route_section",
        postgresql_using="gist",
    )
    op.drop_table("route_section")
    op.drop_index(
        "ix_operator_search_vector", table_name="operator", postgresql_using="gin"
    )
    op.drop_table("operator")
    op.drop_table("data_source")
    op.drop_table("calendar")
    op.drop_table("bot_status")
    op.drop_table("bot_dashboard")
    op.drop_table("bank_holiday")
    op.drop_index(
        op.f("ix_active_users_snapshot_timestamp"), table_name="active_users_snapshot"
    )
    op.drop_table("active_users_snapshot")
    # ### end Alembic commands ###
