"""datasource disabled

Revision ID: 6f929a11ad05
Revises: d19d7a16af7a
Create Date: 2025-11-21 10:25:04.439784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f929a11ad05"
down_revision: Union[str, Sequence[str], None] = "d19d7a16af7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_source",
        sa.Column("disabled", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_source", "disabled")
    # ### end Alembic commands ###
