"""cascade timetable

Revision ID: 8c3af6bd1c31
Revises: 62d6cbe3e53c
Create Date: 2025-10-20 23:58:31.042642

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8c3af6bd1c31"
down_revision: Union[str, Sequence[str], None] = "62d6cbe3e53c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("timetable_data_source_version_id_fkey"), "timetable", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "timetable",
        "data_source_version",
        ["data_source_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "timetable", type_="foreignkey")
    op.create_foreign_key(
        op.f("timetable_data_source_version_id_fkey"),
        "timetable",
        "data_source_version",
        ["data_source_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###
