"""no operator on timetable

Revision ID: 9f24cf1e9752
Revises: 5d97f16c4122
Create Date: 2025-10-20 08:49:35.788833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f24cf1e9752"
down_revision: Union[str, Sequence[str], None] = "5d97f16c4122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("timetable_operator_id_fkey"), "timetable", type_="foreignkey"
    )
    op.drop_column("timetable", "operator_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timetable",
        sa.Column("operator_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("timetable_operator_id_fkey"),
        "timetable",
        "operator",
        ["operator_id"],
        ["id"],
    )
    # ### end Alembic commands ###
