"""vias on service

Revision ID: a368057b82f9
Revises: 4d5b86a8e7c4
Create Date: 2025-09-26 15:32:38.449621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a368057b82f9"
down_revision: Union[str, Sequence[str], None] = "4d5b86a8e7c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("vias", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "vias")
    # ### end Alembic commands ###
