"""op codes

Revision ID: b22a35879bb5
Revises: c6d8d15c169c
Create Date: 2025-11-21 14:14:36.215337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b22a35879bb5"
down_revision: Union[str, Sequence[str], None] = "c6d8d15c169c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_code",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operator_id", "code", name="uq_operator_code_per_operator"
        ),
    )
    op.create_index(
        op.f("ix_operator_code_code"), "operator_code", ["code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operator_code_code"), table_name="operator_code")
    op.drop_table("operator_code")
    # ### end Alembic commands ###
