"""better stopusage

Revision ID: c4086637747c
Revises: 0a6faa54c337
Create Date: 2025-09-28 20:59:53.863310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4086637747c"
down_revision: Union[str, Sequence[str], None] = "0a6faa54c337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_stop_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "service_stop_usage", sa.Column("order", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "service_stop_usage", sa.Column("inbound", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "service_stop_usage", sa.Column("line_name", sa.String(), nullable=True)
    )
    op.add_column(
        "service_stop_usage", sa.Column("timing_point", sa.Boolean(), nullable=True)
    )
    op.create_primary_key("pk_service_stop_usage", "service_stop_usage", ["id"])
    op.execute("CREATE SEQUENCE IF NOT EXISTS service_stop_usage_id_seq")
    op.execute(
        "ALTER TABLE service_stop_usage ALTER COLUMN id SET DEFAULT nextval('service_stop_usage_id_seq')"
    )

    op.create_index(
        "ix_stopusage_inbound_order",
        "service_stop_usage",
        ["inbound", "order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stopusage_inbound_order", table_name="service_stop_usage")
    op.drop_column("service_stop_usage", "timing_point")
    op.drop_column("service_stop_usage", "line_name")
    op.drop_column("service_stop_usage", "inbound")
    op.drop_column("service_stop_usage", "order")
    op.drop_column("service_stop_usage", "id")
    # ### end Alembic commands ###
