"""slugs

Revision ID: c6d8d15c169c
Revises: 6f929a11ad05
Create Date: 2025-11-21 10:43:37.100519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6d8d15c169c"
down_revision: Union[str, Sequence[str], None] = "6f929a11ad05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locality", sa.Column("slug", sa.String(), nullable=True))
    op.create_unique_constraint(None, "locality", ["slug"])
    op.add_column("operator", sa.Column("slug", sa.String(), nullable=True))
    op.create_unique_constraint(None, "operator", ["slug"])
    op.add_column("service", sa.Column("slug", sa.String(), nullable=True))
    op.create_unique_constraint(None, "service", ["slug"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service", type_="unique")
    op.drop_column("service", "slug")
    op.drop_constraint(None, "operator", type_="unique")
    op.drop_column("operator", "slug")
    op.drop_constraint(None, "locality", type_="unique")
    op.drop_column("locality", "slug")
    # ### end Alembic commands ###
