"""operator mode

Revision ID: cef4d1bf8987
Revises: f38ff4b0a3d8
Create Date: 2025-11-16 17:26:28.782376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cef4d1bf8987"
down_revision: Union[str, Sequence[str], None] = "f38ff4b0a3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operator", sa.Column("mode", sa.String(), nullable=True))
    op.create_unique_constraint(None, "operator", ["noc"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "operator", type_="unique")
    op.drop_column("operator", "mode")
    # ### end Alembic commands ###
