"""do not constrain journey and seq

Revision ID: d19d7a16af7a
Revises: cef4d1bf8987
Create Date: 2025-11-20 18:02:08.725286

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d19d7a16af7a"
down_revision: Union[str, Sequence[str], None] = "cef4d1bf8987"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_stop_time_journey_sequence"), "stop_time", type_="unique"
    )
    op.create_index(
        "ix_stoptime_journey_seq",
        "stop_time",
        ["journey_id", "stop_sequence"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stoptime_journey_seq", table_name="stop_time")
    op.create_unique_constraint(
        op.f("uq_stop_time_journey_sequence"),
        "stop_time",
        ["journey_id", "stop_sequence"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
