"""add dynamic headsigns

Revision ID: dc88f769ed36
Revises: 6936d9c17187
Create Date: 2025-09-19 09:54:10.674840

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc88f769ed36'
down_revision: Union[str, Sequence[str], None] = '6936d9c17187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('headsign', sa.String(), nullable=True))
    op.add_column('stop_time', sa.Column('dest_display', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_time', 'dest_display')
    op.drop_column('journey', 'headsign')
    # ### end Alembic commands ###
