"""service mode

Revision ID: f098f428dd0e
Revises: 8c3af6bd1c31
Create Date: 2025-10-24 12:19:59.635561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f098f428dd0e"
down_revision: Union[str, Sequence[str], None] = "8c3af6bd1c31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("mode", sa.String(), nullable=True))
    op.create_index(op.f("ix_service_mode"), "service", ["mode"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_mode"), table_name="service")
    op.drop_column("service", "mode")
    # ### end Alembic commands ###
