"""no more active user stuff

Revision ID: f38ff4b0a3d8
Revises: f098f428dd0e
Create Date: 2025-11-14 10:03:26.363359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f38ff4b0a3d8"
down_revision: Union[str, Sequence[str], None] = "f098f428dd0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_active_users_snapshot_timestamp"), table_name="active_users_snapshot"
    )
    op.drop_table("active_users_snapshot")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_users_snapshot",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_connections", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "unique_connections", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("timestamp", name=op.f("active_users_snapshot_pkey")),
    )
    op.create_index(
        op.f("ix_active_users_snapshot_timestamp"),
        "active_users_snapshot",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###
