"""public use can be null

Revision ID: f7301fc58e0c
Revises: 93bd3a53a2c8
Create Date: 2025-09-25 14:34:10.313024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7301fc58e0c"
down_revision: Union[str, Sequence[str], None] = "93bd3a53a2c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service", "public_use", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "timetable", "public_use", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("service", "public_use", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "timetable", "public_use", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
