"""no slugs for now :(

Revision ID: fd906b6f232e
Revises: 55c3035634ec
Create Date: 2025-09-23 10:04:26.834957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd906b6f232e"
down_revision: Union[str, Sequence[str], None] = "55c3035634ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_line_slug"), "line", type_="unique")
    op.drop_column("line", "slug")
    op.drop_constraint(op.f("uq_locality_slug"), "locality", type_="unique")
    op.drop_column("locality", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locality",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_locality_slug"),
        "locality",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "line",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_line_slug"), "line", ["slug"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
